remote_theme: jekyll/minima
title: mini lang's homepage
description: The official mini language website
author: mini-lang
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-avatar
