remote_theme: jekyll/minima
title: mini lang's homepage
description: The official mini programming language website
author: WilliamRagstad
permalink: /:path/:title
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-avatar
